# Generated by Django 6.0.6 on 2026-06-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(max_length=300, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Foto')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
            ],
        ),
    ]
