# Generated by Django 6.0.6 on 2026-06-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='colors',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
